21-rails-review/revengers/config/routes.rb
Rails.application.routes.draw do


  resources :revengers
  # root to:"revengers#welcome"
  get '/', to:"revengers#welcome"
  #index
  # get '/revengers', to:"revengers#index"
  # get '/revengers/new', to:"revengers#new"
  # get '/revengers/:id', to:"revengers#show"
  # get '/revengers/:id/edit', to:"revengers#edit"
  #
  # post '/revengers', to:"revengers#create"
  # delete '/revengers', to:"revengers#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

21-rails-review/revengers/app/models/organization.rb
class Organization < ApplicationRecord
  has_many :revengers
end

21-rails-review/revengers/app/models/revenger.rb
class Revenger < ApplicationRecord
  belongs_to :organization
  validate :custom_method_right_here


  def custom_method_right_here
    if (self.alias == "")
      errors[:base] << "This person is invalid because NOT OKAY 2019"
    end
  end


end

21-rails-review/revengers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

21-rails-review/revengers/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
end

21-rails-review/revengers/app/controllers/revengers_controller.rb
class RevengersController < ApplicationController
  before_action :find_the_revenger, only: [:show, :edit, :destroy]

  def index
    #model
    @revengers = Revenger.all
    #resp
    #render :index
  end

  def welcome
    #render :welcome
  end

  def new
    @revenger = Revenger.new
    @orgz = Organization.all
    # render :new
  end

  def create
    revenger = Revenger.create(revenger_params)
    if revenger.valid?
      redirect_to revengers_path
    else
      #store the errors for one more request thanks FLASH ⚡️
      flash[:errors] = revenger.errors.full_messages
      redirect_to new_revenger_path
    end

  end

  def show
    render :show
  end

  # get '/revengers/:id/edit'
  def edit
    #model

    @orgz = Organization.all
    # response
    render :edit
  end

  # delete '/revengers/:id'
  def destroy
    @revenger.destroy
    redirect_to revengers_path
  end

  private

  def revenger_params
    params.require(:revenger).permit(:alias, :planet, :organization_id)
  end


  def find_the_revenger
    @revenger = Revenger.find(params[:id])
  end
end

21-rails-review/revengers/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

21-rails-review/revengers/app/helpers/revengers_helper.rb
module RevengersHelper
end

21-rails-review/revengers/app/views/revengers/_form.erb
<ol>
  <% if flash[:errors] %>
    <% flash[:errors].each do |err| %>
        <li><%= err %></li>
    <% end %>
  <% end %>
</ol>

<%= form_for @revenger do |f| %>
  <%= f.label :alias %>
  <%= f.text_field :alias %>
  <%= f.label :planet %>
  <%= f.text_field :planet %>
  <%= f.label "orgz" %>
  <!-- 1. object for the collection select WITH the f. first arg is going to be from the form_for
    2. KEY in the params -- what you want in the params[:2ndarg]
    3. Iterate over what???
    4. VALUE in the params this is a method call
    5. WHAT WILL THE USER SEEEEEEEE?? psst also method call
    6. optional argument prompt: true
  -->

  <%= f.collection_select(:organization_id, @orgz, :id, :name)%>
  <%= f.submit %>
<% end %>

21-rails-review/revengers/app/views/revengers/edit.erb
<h2> upgrade ya</h2>


<%= render "form" %>

21-rails-review/revengers/app/views/revengers/index.erb
<h1> YEET</h1>

  <p> OR make a new one :)</p>
  <%= link_to "NEWWWWW revenger 😈", new_revenger_path%>

<ol>
<% @revengers.each do |r| %>
  <%= link_to r.alias, revenger_path(r) %>
  <%= button_to "vanquish", "/revengers/#{r.id}", {method: :delete} %>
  <%= button_to "upgrade #{r.alias}", "/revengers/#{r.id}/edit", {method: :get} %>
<% end %>
</ol>

21-rails-review/revengers/app/views/revengers/new.erb
<h1> make a new one your org needs more POWER 🌙 </h1>

<%= render "form" %>

21-rails-review/revengers/app/views/revengers/show.erb
<%= link_to "home 🏡", '/revengers' %>

21-rails-review/revengers/app/views/revengers/welcome.erb
yeet